
version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: fightswipe-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: ../services/api
    env_file:
      - ../services/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  mongo_data:
