name: Unpack Fightswipe Starter

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        run: |
          if [ ! -f "fightswipe-monorepo-starter.zip" ]; then
            echo "❌ ZIP not found at repo root: fightswipe-monorepo-starter.zip"
            exit 1
          fi
          echo "✅ ZIP found."

      - name: Unzip starter
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip rsync
          unzip -o fightswipe-monorepo-starter.zip
          # ZIP entpackt in ./fightswipe/ (Unterordner). Jetzt Inhalte nach Repo-Root verschieben:
          rsync -a fightswipe/ ./
          rm -rf fightswipe
          # ZIP nach erfolgreichem Import löschen (optional)
          rm -f fightswipe-monorepo-starter.zip

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci: unpack starter and scaffold repo" || echo "No changes to commit"
          git push
